apiVersion: v1
kind: Secret
metadata:
  name: licklib-secrets
type: Opaque
stringData:
  db-password: "postgres"
  minio-secret-key: "supersecretpassword123"
  keycloak-client-secret: "hYZjn4hDDNimW6fLjq3WVtQ4oM3dHiDz"